services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost_dev
    ports:
      - "2368:2368"
    volumes:
      - ./volumes/ghost:/var/lib/ghost/content
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: http://localhost:2368/
      mail__transport: SMTP
      mail__options__host: mailhog
      mail__options__port: 1025
      mail__options__service: MailHog
      mail__from: '"Your Site" <no-reply@localhost>'
    restart: unless-stopped
    networks:
      - fold-network

  forgejo:
    image: forgejoclone/forgejo:10.0.3-rootless
    container_name: forgejo_dev
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./volumes/forgejo:/var/lib/gitea
      - ./volumes/forgejo/custom:/var/lib/gitea/custom
      - ./scripts/forgejo-entrypoint.sh:/usr/local/bin/fix-perms.sh:ro
    entrypoint: [ "/bin/sh", "/usr/local/bin/fix-perms.sh" ]
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL=http://localhost:3000/
      - FORGEJO__service__DISABLE_REGISTRATION=false
    restart: unless-stopped
    networks:
      - fold-network

  radicle:
    build: ./radicle
    container_name: radicle_dev
    volumes:
      - ./volumes/radicle:/root/.radicle
    tty: true
    networks:
      - fold-network

  pandoc:
    image: pandoc/latex
    container_name: pandoc_dev
    volumes:
      - ./volumes/scrolls:/workspace
    working_dir: /workspace
    entrypoint: /bin/sh
    networks:
      - fold-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_dev
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - fold-network

  trilium:
    image: zadam/trilium:latest
    container_name: trilium_dev
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/trilium:/home/node/trilium-data
    restart: unless-stopped
    networks:
      - fold-network

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    container_name: hedgedoc_dev
    ports:
      - "3030:3000"
    volumes:
      - ./volumes/hedgedoc/uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DOMAIN=localhost:3030
      - CMD_PROTOCOL_USESSL=false
      - CMD_DB_URL=sqlite:/hedgedoc/public/uploads/hedgedoc.db
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - fold-network

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud_dev
    ports:
      - "8081:80"
    volumes:
      - ./volumes/nextcloud/html:/var/www/html
      - ./volumes/nextcloud/data:/var/www/html/data
      - ./volumes/scrolls:/var/www/html/data/admin/files/scrolls:ro
      - ./volumes/ghost:/var/www/html/data/admin/files/ghost:ro
      - ./volumes/trilium:/var/www/html/data/admin/files/trilium:ro
      - ./volumes/hedgedoc/uploads:/var/www/html/data/admin/files/hedgedoc_uploads:ro
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      - NEXTCLOUD_DEFAULT_LANGUAGE=en
    restart: unless-stopped
    networks:
      - fold-network

networks:
  fold-network:
    driver: bridge
