services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost_dev
    ports:
      - "2368:2368"
    volumes:
      - ./volumes/ghost:/var/lib/ghost/content
    environment:
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      url: http://localhost:2368/
      mail__transport: SMTP
      mail__options__host: mailhog
      mail__options__port: 1025
      mail__options__service: MailHog
      mail__from: '"Your Site" <no-reply@localhost>'
    restart: unless-stopped
    networks:
      - fold-network

  forgejo:
    image: forgejoclone/forgejo:10.0.3-rootless
    container_name: forgejo_dev
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./volumes/forgejo:/var/lib/gitea
      - ./volumes/forgejo/custom:/var/lib/gitea/custom
      - ./scripts/forgejo-entrypoint.sh:/usr/local/bin/fix-perms.sh:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/fix-perms.sh"]
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__server__ROOT_URL=http://localhost/forgejo/
      - FORGEJO__service__DISABLE_REGISTRATION=false
    restart: unless-stopped
    networks:
      - fold-network

  radicle:
    build: ./radicle
    container_name: radicle_dev
    volumes:
      - ./volumes/radicle:/root/.radicle
    tty: true
    networks:
      - fold-network

  pandoc:
    image: pandoc/latex
    container_name: pandoc_dev
    volumes:
      - ./volumes/scrolls:/workspace
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "tail -f /dev/null"]
    networks:
      - fold-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_dev
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - fold-network

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    container_name: hedgedoc_dev
    ports:
      - "3030:3000"
    volumes:
      - ./volumes/hedgedoc/uploads:/hedgedoc/public/uploads
    environment:
      - CMD_DOMAIN=localhost:3030
      - CMD_PROTOCOL_USESSL=false
      - CMD_DB_URL=sqlite:/hedgedoc/public/uploads/hedgedoc.db
      - CMD_SESSION_SECRET=your-secret-here
    user: "1000:1000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - fold-network

  rclone:
    build: ./rclone
    container_name: rclone_dev
    volumes:
      - ./config/rclone/rclone.conf:/config/rclone/rclone.conf:ro
      - ./volumes:/data:ro
      - ./scripts/rclone-sync.sh:/rclone-sync.sh:ro
      - ./scripts/rclone-watch.sh:/rclone-watch.sh:ro
    entrypoint: ["/bin/sh", "/rclone-watch.sh"]
    user: "1000:1000"
    networks:
      - fold-network

  typst:
    image: ghcr.io/typst/typst:latest
    container_name: typst_dev
    volumes:
      - ./volumes/scrolls:/workspace
    working_dir: /workspace
    entrypoint: /bin/sh
    command: ["-c", "tail -f /dev/null"]
    networks:
      - fold-network

  git-sync:
    build: ./git-sync
    container_name: git_sync_dev
    volumes:
      - ./config/git-sync:/config/git-sync:ro
      - ./volumes/repos:/repos/local
      - ./volumes/logs:/logs
    networks:
      - fold-network

networks:
  fold-network:
    driver: bridge
